# Map Configuration: Extinction
MapName=Extinction_WP
DisplayName=Extinction
SaveDir=ARK-ex
GamePort=7777
QueryPort=27015
RCONPort=27020
MaxPlayers=70
AdminPassword=CHANGE_ME
ServerPassword=
ModIDs=
CustomStartParams=-NoBattlEye -crossplay -NoHangDetection
ClusterID=
